---
firewall_allowed_tcp_ports:
  - "22"
  - "80"
  - "443"
  - "8080" # eXist-db test instance

java_packages:
  - openjdk-11-jdk

apache_mods_enabled:
  - rewrite.load
  - ssl.load
  - headers.load
  - proxy.load
  - proxy_http.load
  - proxy_http2.load
  - authz_groupfile.load
  - dav.load
  - dav_lock.load
  - dav_fs.load
  - dav_fs.conf

apache_remove_default_vhost: true
apache_vhosts:
  - servername: "{{ ansible_fqdn }}"
    documentroot: "{{ dav_root }}"
    allow_override: "None"
    extra_parameters: |
      {{ zdl_apache_vhost_config }}

zdl_api_context_paths:
  - /articles/exist
  - /articles/forms
  - /articles/index
  - /articles/issues
  - /articles/search
  - /assets
  - /home
  - /status

zdl_apache_vhost_config: |
  ErrorLog ${APACHE_LOG_DIR}/error.log
  CustomLog ${APACHE_LOG_DIR}/access.log combined

  <Location />
    AuthType Basic
    AuthName ZDL-Lex-Server
    AuthUserFile htpasswd
    AuthGroupFile htgroup

    Require valid-user

    RequestHeader set X-Remote-User %{REMOTE_USER}s
  </Location>

  <DirectoryMatch ^\.|\/\.>
    Order allow,deny
    Deny from all
  </DirectoryMatch>

  Alias /zdl-lex-client {{ lex_client_dir }}
  <Location /zdl-lex-client>
    Options +Indexes
    Require all granted
  </Location>

  Alias /articles {{ dav_root }}
  <Location /articles>
    Dav On
    DavDepthInfinity on

    Options +Indexes

    Require group Lexikographen
  </Location>

  RedirectMatch ^/$ /home

  ProxyTimeout 300

  {% for cp in zdl_api_context_paths %}
  <Location {{ cp }}>
    ProxyPass http://localhost:3000{{ cp }} retry=0
    ProxyPassReverse http://localhost:3000{{ cp }}
  </Location>
  {% endfor %}

  <Location /solr>
    ProxyPass http://localhost:8983/solr retry=0
    ProxyPassReverse http://localhost:8983/solr
    Require group admin
  </Location>

  <Location /exist>
    ProxyPass http://spock.dwds.de:8080/exist retry=0
    ProxyPassReverse http://spock.dwds.de:8080/exist
    Require group Lexikographen
    #Order Allow,Deny
    #Deny from all
  </Location>

solr_version: "7.7.1"
solr_timezone: "Europe/Berlin"
solr_cores:
  - "articles"

lex_client_dir: "/home/lex/zdl-lex-client"
lex_data_dir: "/var/lex"

dav_root: "{{ lex_data_dir }}/git/articles"

zdl_lex_version: "{{ lookup('file', '../VERSION') }}"
