---
firewall_allowed_tcp_ports:
  - "22"
  - "80"
  - "443"
  - "8080" # eXist-db test instance

java_packages:
  - openjdk-11-jdk

apache_mods_enabled:
  - rewrite.load
  - ssl.load
  - headers.load
  - proxy.load
  - proxy_http.load
  - proxy_http2.load
  - authz_groupfile.load
  - dav.load
  - dav_lock.load
  - dav_fs.load
  - dav_fs.conf

apache_remove_default_vhost: true
apache_vhosts:
  - servername: "{{ ansible_fqdn }}"
    documentroot: "{{ dav_root }}"
    allow_override: "None"
    extra_parameters: |
      {{ zdl_apache_vhost_config }}

zdl_api_context_paths:
  - /articles/forms
  - /assets
  - /statistics

zdl_apache_vhost_config: |
  <Location />
    AuthType Basic
    AuthName ZDL-Lex-Server
    AuthUserFile htpasswd
    AuthGroupFile htgroup

    Require valid-user
  </Location>

  <DirectoryMatch ^\.|\/\.>
    Order allow,deny
    Deny from all
  </DirectoryMatch>

  Alias /articles {{ dav_root }}
  <Location /articles>
    Dav On
    DavDepthInfinity on

    Options +Indexes

    Require group Lexikographen
  </Location>

  RedirectMatch ^/$ /statistics

  {% for cp in zdl_api_context_paths %}
  <Location {{ cp }}>
    ProxyPass http://localhost:3000{{ cp }}
    ProxyPassReverse http://localhost:3000{{ cp }}
  </Location>
  {% endfor %}

  <Location /solr>
    ProxyPass http://localhost:8983/solr
    ProxyPassReverse http://localhost:8983/solr
    Require group admin
  </Location>

solr_timezone: "Europe/Berlin"
solr_cores:
  - "articles"

lex_data_dir: "/var/lex"

dav_root: "{{ lex_data_dir }}/git/articles"
dav_users: []
dav_user_groups: []

zdl_lex_version: "{{ lookup('file', '../VERSION') }}"
