---
firewall_allowed_tcp_ports:
  - "22"
  - "80"
  - "443"

java_packages:
  - openjdk-11-jdk

apache_mods_enabled:
  - rewrite.load
  - ssl.load
  - headers.load
  - proxy.load
  - proxy_http.load
  - proxy_http2.load
  - authz_groupfile.load
  - dav.load
  - dav_lock.load
  - dav_fs.load
  - dav_fs.conf

apache_remove_default_vhost: true
apache_vhosts:
  - servername: "{{ ansible_fqdn }}"
    documentroot: "{{ dav_root }}"
    allow_override: "None"
    extra_parameters: |
      <Location />
        AuthType Basic
        AuthName ZDL-Lex-Server
        AuthUserFile htpasswd
        AuthGroupFile htgroup

        Require valid-user
      </Location>

      <DirectoryMatch ^\.|\/\.>
        Order allow,deny
        Deny from all
      </DirectoryMatch>

      Alias /webdav {{ dav_root }}
      <Location /webdav>
        Dav On
        DavDepthInfinity on

        Options +Indexes

        Require group Lexikographen
      </Location>

      <Location /solr>
        ProxyPass http://localhost:8983/solr
        ProxyPassReverse http://localhost:8983/solr
        Require group admin
      </Location>

      <Location /api>
        ProxyPass http://localhost:3000/api
        ProxyPassReverse http://localhost:3000/api
      </Location>

solr_timezone: "Europe/Berlin"
solr_cores:
  - "articles"

lex_data_dir: "/var/lex"

dav_root: "{{ lex_data_dir }}/git/articles"
dav_users: []
dav_user_groups: []

