((python-mode .  ((python-test-runner . pytest)
                  (pyvenv-workon . "zdl-lex")))
 (clojure-mode . ((cider-preferred-build-tool . "clojure-cli")
                  (cider-clojure-cli-aliases . ":build:clerk:client:corpora:db:dev:excel:oxygen:python:server:test")
                  (cider-ns-code-reload-tool . 'clj-reload)
                  (cider-ns-refresh-before-fn . "user/halt")
                  (cider-ns-refresh-after-fn . "user/go")
                  (cider-ns-refresh-show-log-buffer . t))))
