cuda:
  stage: build
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"
  image: docker:29.6.2
  services:
    - docker:29.6.2-dind
  before_script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login $CI_REGISTRY -u $CI_REGISTRY_USER --password-stdin
  script:
    - docker build -f Dockerfile.cuda -t ${CI_REGISTRY_IMAGE}/cuda:debian13-cuda13 .
    - docker push ${CI_REGISTRY_IMAGE}/cuda:debian13-cuda13
  tags:
    - zdl
    - build

build:
  stage: build
  image: docker:29.6.2
  services:
    - docker:29.6.2-dind
  before_script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login $CI_REGISTRY -u $CI_REGISTRY_USER --password-stdin
  script:
    - docker compose build
    - docker compose push
  only:
    - production
  tags:
    - zdl
    - build

deploy-labor:
  stage: deploy
  image: docker:29.6.2
  services:
    - docker:29.6.2-dind
  before_script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login $CI_REGISTRY -u $CI_REGISTRY_USER --password-stdin
  script:
    - docker compose -f compose.labor.yml pull
    - docker compose -f compose.labor.yml down --remove-orphans
    - docker compose -f compose.labor.yml up -d
  only:
    - production
  tags:
    - labor.dwds.de
    - shell

deploy-gpt:
  stage: deploy
  image: docker:29.6.2
  services:
    - docker:29.6.2-dind
  before_script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login $CI_REGISTRY -u $CI_REGISTRY_USER --password-stdin
  script:
    - docker compose -f compose.gpt.yml pull
    - docker compose -f compose.gpt.yml down --remove-orphans
    - docker compose -f compose.gpt.yml up -d
  only:
    - production
  tags:
    - zdl-gpu01.bbaw.de
    - shell

dwdswb:
  stage: deploy
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"
  image: python:3.13
  script:
    - pip install --root-user-action ignore -r requirements/dwdswb.txt
    - python -m zdl_lex.wb.package
  tags:
    - zdl
    - build
