default:
  image: docker:26.1.0
  services:
    - docker:26.1.0-dind
  before_script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login $CI_REGISTRY -u $CI_REGISTRY_USER --password-stdin

build:
  stage: build
  script:
    - docker compose build
    - docker compose push
  only:
    - main
  tags:
    - zdl
    - build

deploy-labor:
  stage: deploy
  script:
    - docker compose -f compose.labor.yml pull
    - docker compose -f compose.labor.yml down --remove-orphans
    - docker compose -f compose.labor.yml up -d
  only:
    - main
  tags:
    - labor.dwds.de
    - shell

deploy-gpt:
  stage: deploy
  script:
    - docker compose -f compose.gpt.yml pull
    - docker compose -f compose.gpt.yml down --remove-orphans
    - docker compose -f compose.gpt.yml up -d
  only:
    - main
  tags:
    - zdl-gpu01.bbaw.de
    - shell
