version: '3.4'
services:
  basex:
    image: basex/basexhttp:latest
    container_name: basex
    ports:
        - 1984:1984
        - 8984:8984
    networks:
      - www
    volumes:
      - type: volume
        source: data
        target: /srv/basex/data
      - type: bind
        source: ./data
        target: /srv/production-data

volumes:
  data:
    driver: local
    name: basex-data

networks:
  www:
    driver: bridge
