FROM gitup.uni-potsdam.de:4567/zentrum-lexikographie/lex/clojure:debian13

WORKDIR /nlp

COPY requirements/nlp.txt requirements.txt

RUN --mount=type=cache,target=/root/.cache/pip \
    --mount=type=secret,id=gitup-netrc,dst=/root/.netrc \
    pip install  --root-user-action ignore -r requirements.txt

#COPY ./ .
