version: "3"
services:
  solr:
    image: docker-registry.zdl.org/zdl-lex/solr
    build:
      context: ./docker/solr
      dockerfile: Dockerfile
    volumes:
      - index:/var/solr
    ports:
      - "8983:8983"
  gpt:
    image: docker-registry.zdl.org/zdl-lex/gpt
    build:
      context: ./docker/gpt
      dockerfile: Dockerfile
    command:
      - "--chat_format"
      - "chatml"
      - "--model_alias"
      - "discolm"
      - "--model"
      - "/models/discolm_german_7b_v1.Q4_K_M.gguf"
    volumes:
      - ./models:/models
    ports:
      - "8000:8000"
  server:
    image: docker-registry.zdl.org/zdl-lex/server
    build:
      context: .
      dockerfile: docker/server/Dockerfile
    environment:
      - "ZDL_LEX_SOLR_URL=http://solr:8983/solr/"
      - "ZDL_LEX_GIT_DIR=/data/git"
      - "ZDL_LEX_LOCK_DB_PATH=/data/locks"
    volumes:
      - server:/data
    ports:
      - "3000:3000"
volumes:
  index:
  server:
