FROM nvidia/cuda:13.3.1-base-ubuntu26.04

# Install Python

RUN apt-get update && \
    apt-get install -y \
    git \
    python3-full \
    python3-pip \
    python3-dev \
    python-is-python3 && \
    rm -rf /var/lib/apt/lists/*

RUN python3 -m venv /venv

ENV PATH="/venv/bin:$PATH"

# Install Java/Clojure
#
# https://github.com/Quantisan/docker-clojure/blob/master/target/debian-trixie-slim-26/tools-deps/Dockerfile

ENV JAVA_HOME=/opt/java/openjdk
COPY --from=eclipse-temurin:26 $JAVA_HOME $JAVA_HOME
ENV PATH="${JAVA_HOME}/bin:${PATH}"

ENV CLOJURE_VERSION=1.12.5.1664

WORKDIR /tmp

RUN \
    apt-get update && \
    apt-get install -y curl make git rlwrap && \
    rm -rf /var/lib/apt/lists/* && \
    curl -fsSLO https://download.clojure.org/install/linux-install-$CLOJURE_VERSION.sh && \
    sha256sum linux-install-$CLOJURE_VERSION.sh && \
    echo "fb2f0ce23373d64bb4f13fce2ce2924c54ee0c033755357900808a1250621d82 *linux-install-$CLOJURE_VERSION.sh" | sha256sum -c - && \
    chmod +x linux-install-$CLOJURE_VERSION.sh && \
    ./linux-install-$CLOJURE_VERSION.sh && \
    rm linux-install-$CLOJURE_VERSION.sh && \
    clojure -e "(clojure-version)" && \
    apt-get purge -y --auto-remove curl

# Install pipeline

WORKDIR /nlp

COPY requirements.nlp.txt .

RUN --mount=type=cache,target=/root/.cache/pip \
    --mount=type=secret,id=gitup-netrc,dst=/root/.netrc \
    pip install  -r requirements.nlp.txt

#COPY ./ .
