FROM solr:9

ENV SOLR_MODULES=analysis-extras

ADD --chown=8983:8983\
    solr/managed-schema.xml\
    /opt/solr/server/solr/configsets/_default/conf/managed-schema.xml

ADD --chown=8983:8983\
    solr/stopwords_de.txt\
    /opt/solr/server/solr/configsets/_default/conf/lang/stopwords_de.txt
