TOKENIZATION_EXCEPTIONS = (
    # whitelist of capitalized chars within words
    u'SonntagsBlick', u'McCarthy-Ära', u'(WoW)', u'AfD.',
    u'FrischeKiste', u'GraWe', u'McEnroe', u'HochschulabsolventInnen',
    u'(TransMIT)', u'BayBG', u'KfZ-Zulieferers',
    u'»BiF«', u'NeuLand', u'eRikm', u'YouGov-Umfrage', u'GoSMS',
    u'(MfS)', u'McCormack)', u'(SchwbG)', u'HipHop-Künstler',
    u'DeLillos', u'(IGfM)', u'(vCJD),', u'KaDeWe', u'HändlerInnen',
    u'YouTube-Szene', u'YouTube-Trends', u'YouTubes',
    u'YouTube.', u'DuVernay', u'LiMo', u'GründerInnen',
    u'KapitalgeberInnen', u'DradioWissen', u'StGB.',
    u'ExVira', u'(ExVira', u'eBook-Konvertierung',
    u'StrÄndG)', '(BGBl.', u'PiCTeX', u'iOS)', u'YouTuber',
    u'McQueen.', u'(StGB.', u'(IStGH)', u'(BetrVG)', u'MdF',
    u'McDonald’s,', u'EyePhone,', u'McClelland', u'AT&T',
    u'AutorInnen', u'(BauGB)', u'BauGB)', u'mPFC', u'DeClercq',
    u'BamS-Reporterin', u'iPhones,', 'WhatsApp,', u'AnwenderInnen',
    u'DoubleClick', u'BtMG', u'(DroLeg)', u'C&A', u'»PPmP',
    u'CarPlay', u'McKinsey.', u'RecRec)', u'McCartney,',
    u'McAleese,', u'S.A.-Männer.', u'CvD', u'FoodCenter,',
    u'BdBSt', u'WStB),', u'BdBSt).', u'MyBibRSS', u'cSt',
    u'YouTube,', u'AfD', u'AutoCAD-Test', u'eBook', u'(DStV)',
    u'(BfArM)', u'GutsMuths', u'GlücksritterInnen', u'(DiS)',
    u'McKinsey-Studien', u'openSUSE', u'(VoIP)', u'McClaren.',
    u'cSt,', u'hiLDEBRANDT:', u'HbbTV', u'HfÖ', u'OpenType',
    u'GitHub-Anwendungsfall', u'AussiedlerInnen', u'BürgerInnen',
    u'StS.', u'(StS.)', u'AirPlay', u'(iOS)', u'KPdSU,',
    u'AngehörigenInnen', u'»eBook«', u'neu(st)e', u'L’Empéri',
    u'»Lunch In Time«-Menü,', u'McDonald’s', u'InterContintal-Hotels',
    u'LuftBO)', u'grM', u'BetrVG', u'(BfR)', u'(kW)', u'mmHg',
    u'TüV-Gebühren,', u'FotoStation', u'»AutoAusfüllen«,', u'(BdV),',
    u'»TextMaker', u'OpenOffice.org', u'Word-AutoFormen', u'(BaT),',
    u'»iPhone', u'UdK', u'iPad,', u'McGill', u'TeamBank-Chef',
    u'BgVV.', u'MgT', u'HfG', u'StVO,', u'StVO', u'McKean',
    u'EuroStoxx', u'(BfV),', u'Drive-in-McDonalds', u'MigrantInnen,',
    u'»PdR«', u'(StGB)', u'WikiLeaks', u'(SoFFin)', u'iCraveTV',
    u'EM.TV', u'HipHop', u'McAfee', u'KaZaA', 'eMule', u'MacBook',
    u'O-TonArt,', u'SammlerInnen', u'JavaScript-Programm', u'BaFin',
    u'McAllister', u'IfZ-Team.', u'(SdK),', u'KirchMedia,',
    u'SinnLeffers-Modehäuser', u'McCain,', u'McGee', u'McKibben',
    u'(An-)Sprache.', u'KeePass,', u'iPhone', u'CompuServe',
    u'»CompuServe', u'(NewsGroups)', u'ImmOnline', u'iPad', u'iOS',
    u'McDonaldʼs', 'McGuire', u'»BerlinOnline.de«', u'HypoVereinsbank',
    u'(GmbH)', u'MfNV', u'DeTeMedien', u'BfG', u'MfS,', u'MfS-Zwecke',
    u'StGB)', u'StGB),', u'kWh', u'McNair,', u'MfS-Spionin',
    u'sFr', u'sFr).', u'WestLB', u'iPod', u'HaMü', u'ComicLiteratur',
    u'S.S.', u'SystemConsult', u'VfGH,', u'OʼNeill', u'KaDeWe.',
    u'McBeal«', u'StGB,', u'BayernLB,', u'McDonald-Hamburger-Kette',
    u'OʼConnor', u'LeMay', u'eBay', u'mbH', u'HipHop,', u'MoMA',
    u'McDonaldʼs-Filiale;', u'WikiWeb', u'AdW', u'»WorldCom«',
    u'λ-Phagen', u'¬p', u'KPdSU.', u'GmbH.', u'eG', u'DrKW', u'LfU',
    u'(BVfS),', u'(HeLP)', u'InnoTrans', u'TransFair-Geschäftsführer',
    u'IgE-Antikörper', u'VfL', u'McCartney', u'»Peanuts«-Geschichten',
    u'kW', u'GeV', u'PiS', u'kJ.', u'MfS-Offizieren', u'InsO',
    u'MfS', u'(KPdSU).', u'KPdSU', u'Frankfurt/Oder',
    u'UdSSR', u'»DHfK', u'(BBiG)', u'(VaR)', u'BayernLB', u'VfB',
    u'ActiveX', u'JavaScript', u'CeBIT', u'CeBit', u'YouTube',
    u'StepStone', u'UdSSR,', u'KfW-Gesetzes', u'ProSieben',
    u'SkyDrive-Cloud', u'McCarthy', u'HiFi-Videorekorder',
    u'»Deutschland-Investitions-GmbH«', u'(StPO).', u'(KfW),',
    u'ThyssenKrupp', u'ActiveX-Control,', u'eGK', u'UdSSR;',
    u'F.A.Z.-Aktienindex', u'AntiLobby-Gesetzgebung',
    u'DeutschlandPremiere.', u'»Oscar«-Kandidaten',
    u'(eCommerce)', u'eLearning', u'CyberSurfr', u'OpenOffice',
    u'(BfA)', u'BfA«', u'EnBW,', u'AktG).', u'GmbH', u'GmbH«',
    u'BetriebVG.', u'TuS', u'MdB,', u'OpenSource-affine-Firmen-WG',
    u'(AsF)', u'Robert-Bosch-GmbH', u'eGmbH«.', u'BlueHybrid', u'GmbH,',
    u'S.S.-Männer', u'BenQ', u'FlexScan', u'UdSSR:', u'PopArt',
    u'MfS-Gliederungen', u'MfS-Zentrale', u'BfA', u'BvR',
    u'KüSchG', u'F.A.Z.', u'vH', u'vH.', u'(BWpV)', u'iPad?',
    u'GdP-Bundesvorsitzende', u'eSwiss', u'(GfN)',
    u'KitKat«', u'KitKat-Break', u'KitKat-Pause,', u'iTunes',
    u'BamS', u'(DuMont)', u'AVerErgG', u'TubeAgency.',
    u'@-Zeichen', u'@Benutzername«', u'VfB-Chefs',
    u'FußballBundes', u'»großmäulige(n)', u'BdL,',
    u'McKinsey-Studie', u'(GdP)', u'(Ost-)Berliner',
    u'AufenthG;', u'DeutschlandRadio', u'SiCon',
    u'VfB,', u'MfS«:', u'MfS-Offiziere', u'AStA', u'(AStA)',
    u'AStA,', u'ContiTech', u'(BoA)', u'kWh', u'kWh/m²',
    u'MicroLink', u'dLAN', u'iMac', u'»SprecherInnenrat«', u'DaZ',
    u'SmartCard', u'TechniSat', u'TomTom', u'McGregor.',
    u'McCreesh,', u'KarstadtQuelle', u'HipHop-', u'sFr.', u'sFr.;',
    u'DeLillo', u'McCarthy-Romane', u'Apple-iPhone.', u'OʼMalley,',
    u'OʼNan', u'literaturWERKstatt', u'CompuServe.', u'»FreePen«.',
    u'(KfW)', u'(F.A.Z.', u'DaimlerChrysler', u'VfL.', u'kBit/s',
    u'RuleML', u'iPhone-Modelle', u'DigiTex', 'GmbH;', u'EnBW',
    u'Verlags-GmbH', u'»SpVgg', u'SonntagsBlick-Autor',
    u'EuroStoxx50', u'(BVerwG)', u'(BVwG)', u'(BVerfG),',
    u'BVerfGG).', u'BfV', u'KirchMedia', u'ProSiebenSat.1',
    u'BesucherInnen', u'MdIs', u'(BkmU', u'MultiThématiques',
    u'(http://www.Siicom.Com/odrazb/).', u'iPod-Interface',
    u'(KaDeWe)', u'(EuGH)', u'EinwanderInnen', u'EuGH',
    u'WhatsApp', u'StGB', u'(TeV)', u'KundInnen', u'HipHoper.',
    u'BvS', u'MitarbeiterInnen', u'eBusiness', u'MathInBraille',
    u'GründerIdeenMesse.', u'TecDax-Unternehmen', u'DaShaun',
    u'AStAs', u'FreeYellow-Server', u'McKeown,', u'(VfGH)',
    u'»Macworld«.', u'MeinFernbus', u'StarWriter', u'StarCalc.',
    u'(KiKA)', u'WordPress', u'SumTotal', u'aXos', u'(BvS).',
    u'ThyssenKrupp,', u'LinkedIn', u'GdED', u'ThyssenKrupp-Konzern',
    u'TravelScout24', u'(WoGeHe)', u'McCann', u'VfR', u'YouTubern,',
    u'McDonnell', u'GfK-Experte.', u'(KonTraG)',
    u'»UnAufgefordert«', u'AvW', u'9ObA121/06v)', u'derStandard.at',
    u'S&P', u'(BaFin)', u'I.S.A.R.', u'MoKo-Leiterin',
    u'RecyclerEdition', u'(IgE).', u'EuroStoxx50-Index.',
    u'WebShop', u'NutzerInnen', u'BellSouth', u'McKinsey', u'KfW',
    u'SoHo', u'»SOuth', u'HOuston', u'M:OOP',
    u'»McDonaldisierung«',
    u'\u200b:-)', u'\u200b:)', u'\u200b:-(',
)
