---
firewall_allowed_tcp_ports:
  - "22"
  - "80"
  - "443"

apache_mods_enabled:
  - rewrite.load
  - ssl.load
  - headers.load
  - proxy.load
  - proxy_http.load
  - proxy_http2.load
  - authz_groupfile.load

apache_remove_default_vhost: true
apache_vhosts:
  - servername: "{{ ansible_fqdn }}"
    documentroot: "/var/www"
    allow_override: "None"
    extra_parameters: |
      {{ zdl_apache_vhost_config }}

zdl_apache_vhost_config: |
  ErrorLog ${APACHE_LOG_DIR}/error.log
  CustomLog ${APACHE_LOG_DIR}/access.log combined

  <Location />
    AuthType Basic
    AuthName ZDL-Lex-Server
    AuthUserFile htpasswd
    AuthGroupFile htgroup

    Require valid-user

    RequestHeader set X-Remote-User %{REMOTE_USER}s
  </Location>

  <DirectoryMatch ^\.|\/\.>
    Order allow,deny
    Deny from all
  </DirectoryMatch>

  RedirectMatch ^/$ /home

  ProxyTimeout 300

  <Location /solr>
    ProxyPass http://localhost:8983/solr retry=0
    ProxyPassReverse http://localhost:8983/solr
    Require group admin
  </Location>

  <Location />
    ProxyPass http://localhost:3000/ retry=0
    ProxyPassReverse http://localhost:3000/
  </Location>

solr_version: "7.7.1"
solr_timezone: "Europe/Berlin"
solr_cores:
  - "articles"

lex_data_dir: "/var/lex"
