---
existdb_user: "existdb"
existdb_group: "existdb"
existdb_shell: "/bin/bash"
existdb_home: "/opt/existdb"

existdb_version: "4.7.1"
existdb_installer_jar: "eXist-db-setup-{{ existdb_version }}.jar" 
existdb_download_url: "https://dl.bintray.com/existdb/releases/{{ existdb_installer_jar }}"
existdb_data_dir: "/var/existdb"
existdb_export_dir: "/var/backups/existdb"
existdb_admin_password: "admin"

existdb_installer_base: "{{ existdb_home }}/.install"
existdb_installer_path: "{{ existdb_installer_base }}/{{ existdb_installer_jar }}"
existdb_installer_options: "{{ existdb_installer_base }}/existdb-installer-options.properties"

existdb_install_service: yes

existdb_max_memory: "{{ (ansible_memtotal_mb * 0.5)|int }}"
existdb_cache_size: "{{ (existdb_max_memory|int * 0.25)|int }}"
existdb_collection_cache_size: "{{ (existdb_max_memory|int * 0.125)|int|abs }}"
existdb_index_buffer_size: "{{ (existdb_max_memory|int * 0.125)|int|abs }}"
existdb_max_connections: "20"
existdb_backup_cron_trigger: "0 0 * * * ?"

existdb_wrapper_conf: "{{ existdb_home }}/tools/yajsw/conf/wrapper.conf"
