---
- hosts: zdl-lex
  tasks:
    - name: Add lex user
      user:
        name: lex
        group: www-data
        groups: git
        home: /home/lex

    - name: Set mode on lex home
      file:
        path: /home/lex
        mode: 0770

    - name: Create data dir
      file:
        path: "{{ lex_data_dir }}"
        state: directory
        owner: lex
        group: www-data
        mode: 0770

    - name: Configure API
      template:
        src: zdl-lex-server.config.edn
        dest: /home/lex
        owner: lex
        group: www-data
        mode: 0660
      register: api_config

    - name: Copy API
      copy:
        src: ../server/target/uberjar/zdl-lex-server-0.1.0-SNAPSHOT-standalone.jar
        dest: /home/lex/zdl-lex-server.jar
        owner: lex
        group: www-data
      register: api_jar

    - name: Install API systemd service
      template:
        src: zdl-lex-server.service
        dest: /etc/systemd/system
      register: api_service

    - name: Enable and restart API service
      systemd:
        name: "zdl-lex-server"
        daemon_reload: "{{ api_service is changed }}"
        enabled: true
        state: restarted
      when: api_config is changed or api_jar is changed or api_service is changed
