---
- hosts: zdl-lex
  tasks:
    - name: Add lex user
      user:
        name: lex
        group: www-data
        groups: git
        home: /home/lex
        shell: /bin/bash

    - name: Set mode on lex home
      file:
        path: /home/lex
        mode: 0770

    - name: Check data dir
      stat:
        path: "{{ lex_data_dir }}"
      register: data_dir

    - name: Create data dir
      file:
        path: "{{ lex_data_dir }}"
        state: directory
        owner: lex
        group: www-data
        mode: 0770

    - name: Configure git
      git_config:
        name: "{{ item.name }}"
        scope: global
        value: "{{ item.value }}"
      with_items:
        - name: "user.name"
          value: "ZDL-Lex"
        - name: "user.email"
          value: "noreply@lex.dwds.de"
      become: True
      become_user: lex

    - name: Clone git repo
      shell: >
        git clone /home/git/lex.git {{ lex_data_dir }}/git
      become: True
      become_user: lex
      when: not data_dir.stat.exists

    - name: Copy test fixture
      shell: >
        cp -R /vagrant/data/git/articles . &&
        git add . &&
        git commit -m "Add test fixture" &&
        git push origin
      args:
        chdir: "{{ lex_data_dir }}/git"
      become: True
      become_user: lex
      when: "('vagrant' in group_names) and (not data_dir.stat.exists)"

    - name: Configure API
      template:
        src: zdl-lex-server.config.env
        dest: /home/lex
        owner: lex
        group: www-data
        mode: 0660
      register: api_config

    - name: Copy API
      copy:
        src: "api/org.zdl.lex.server-standalone.jar"
        dest: /home/lex/zdl-lex-server.jar
        owner: lex
        group: www-data
      register: api_jar

    - name: Install API systemd service
      template:
        src: zdl-lex-server.service
        dest: /etc/systemd/system
      register: api_service

    - name: Enable and restart API service
      systemd:
        name: "zdl-lex-server"
        daemon_reload: "{{ api_service is changed }}"
        enabled: true
        state: restarted
      when: api_config is changed or api_jar is changed or api_service is changed
