# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "debian/contrib-stretch64"
  config.vm.network "private_network", ip: "192.168.33.10"
  config.vm.synced_folder "..", "/vagrant", mount_options: ["dmode=775", "fmode=664", "umask=002"], SharedFoldersEnableSymlinksCreate: false
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "2048"
    vb.default_nic_type = "Am79C973"
  end
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "main.yml"
    ansible.groups = { "zdl-lex" => ["default"],
                       "vagrant" => ["default"] }
    ansible.become = true
    ansible.ask_vault_pass = true
    ansible.compatibility_mode = "2.0"
    ansible.galaxy_command = "ansible-galaxy install --role-file=%{role_file}"
    ansible.galaxy_role_file = "roles.yml"
  end
end
