#!/usr/bin/env python
# encoding: utf-8

# zeitliche Einordnung
DDR           = u'DDR'
HIST          = u'historisch'
NAZ           = u'nazistisch'
VERALTEND     = u'veraltend'
VERALTET      = u'veraltet'

# Stil
ABWERTEND     = u'abwertend'
ALTERTUEMLICH = u'altertümlich'
BILDLICH      = u'bildlich'
DERB          = u'derb'
DICHTERISCH   = u'dichterisch'
GEHOBEN       = u'gehoben'
IRONISCH      = u'ironisch'
LIT           = u'literarisch'
PAPIERDEUTSCH = u'papierdeutsch'
SALOPP        = u'salopp'
SCHERZHAFT    = u'scherzhaft'
SPOETT        = u'spöttisch'
UEBERTRAGEN   = u'übertragen'
UGS           = u'umgangssprachlich'
VERHUELL      = u'verhüllend'
VULGAER       = u'vulgär'

# regionale Einordnung
ALEMANN       = u'alemannisch'
BAYRISCH      = u'bayrisch'
BERLIN        = u'berlinisch'
FRAENKISCH    = u'fränkisch'
LANDSCH       = u'landschaftlich'
MITTELDT      = u'mitteldeutsch'
NORDDT        = u'norddeutsch'
OESTERR       = u'östereichisch'
OSTDT         = u'ostdeutsch'
OSTMITTELDT   = u'ostmitteldeutsch'
PREUSS        = u'preußisch'
SCHWEIZ       = u'schweizerisch'
SUEDDT        = u'süddeutsch'
WESTDT        = u'westdeutsch'
WESTMITTELDT  = u'westmitteldeutsch'

# internationale Einordnung
ENGL          = u'englisch'
FRZ           = u'französisch'
GRIECH        = u'griechisch'
ITAL          = u'italienisch'
LATEIN        = u'lateinisch'
LETT          = u'lettisch'
LUXEMB        = u'luxemburgisch'
NIEDERL       = u'niederländisch'
PERS          = u'persisch'
RUMAEN        = u'rumänisch'
RUSS          = u'russisch'
SCHWED        = u'schwedisch'
SLOWAK        = u'slowakisch'
SPAN          = u'spanisch'
TSCHECH       = u'tschechisch'
UNGAR         = u'ungarisch'

# Domänen
BIBEL         = u'biblisch'
BIOLOGIE      = u'Biologie'
DRUCKEREI     = u'Druckerei'
FACHSPRACHE   = u'fachsprachlich'
JAEGER        = u'Jägersprache'
JUGEND        = u'Jugendsprache'
MEDIZIN       = u'Medizin'
MILITAER      = u'Militär'
MUSIK         = u'Musik'
RELIGION      = u'Religion'
SEEMANN       = u'Seemannssprache'

OT_USAGE_MARKERS = {
        u'1420-1422': (HIST, ),
        u'1459-1463': (HIST, ),
        u'1736-1739': (HIST, ),
        u'1813': (HIST, ),
        u'19. Jahrhundert': (HIST, ),
        u'1909 bis 1918': (HIST, ),
        u'1918 bis 1966': (HIST, ),
        u'1920': (HIST, ),
        u'1942': (HIST, ),
        u'1966 bis 1969': (HIST, ),
        u'2011 noch relativ neu': (),
        u'50er Jahre': (HIST, ),
        u'Abschwächung': (),
        u'abwert.': (ABWERTEND, ),
        u'abwertend': (ABWERTEND, ),
        u'eher abwertend': (ABWERTEND, ),
        u'aggressiv': (),
        u'alemann.': (ALEMANN, ),
        u'alemannisch': (ALEMANN, ),
        u'oft abwertend': (ABWERTEND, ),
        u'als Wortbildungspräfix, z.B. scheinselbständig': (),
        u'alt': (VERALTET, ),
        u'altbayr.': (BAYRISCH),
        u'alternative Schreibung': (),
        u'altertümelnd': (ALTERTUEMLICH, ),
        u'altertümelnd oder iron.': (ALTERTUEMLICH, IRONISCH, ),
        u'altertüml.': (ALTERTUEMLICH, ),
        u'altertümlich': (ALTERTUEMLICH, ),
        u'Amtsdeutsch': (PAPIERDEUTSCH, ),
        u'Amtsdeutsch, übertragen': (PAPIERDEUTSCH, UEBERTRAGEN, ),
        u'Amtsdeutsch, veraltend': (PAPIERDEUTSCH, VERALTEND, ),
        u'eher im Amtsdeutsch': (PAPIERDEUTSCH, ),
        u'amerikanisch, stark abwertend': (ABWERTEND, ),
        u'Amtsdeutsch, fig.': (PAPIERDEUTSCH, BILDLICH, ),
        u'amtssprachl.': (PAPIERDEUTSCH, ),
        u'amtssprachlich': (PAPIERDEUTSCH, ),
        u'anat.': (MEDIZIN, ),
        u'Anrede auf Karnevalssitzung': (),
        u'antik': (HIST, ),
        u'Antike': (HIST, ),
        u'Anwaltsdeutsch': (PAPIERDEUTSCH, ),
        u'Arbeitswelt': (),
        u'Arbeitswelt-Jargon': (),
        u'auch iron.': (IRONISCH, ),
        u'auch ironisch': (IRONISCH, ),
        u'auch med.': (MEDIZIN, ),
        u'Ausdauersport': (),
        u'aussterbend, abwertend': (VERALTEND, ABWERTEND, ),
        u'außer Norddtld. verbreitet': (),
        u"Ausspr. 'oki'doki": (),
        u'Baden-Württ.': (FRAENKISCH, ALEMANN, ),
        u'Baden-Württemberg': (FRAENKISCH, ALEMANN, ),
        u'badisch': (ALEMANN, ),
        u'bair.': (BAYRISCH, ),
        u'bairisch/fränkisch':(BAYRISCH, FRAENKISCH, ),
        u'bayerisch': (BAYRISCH, ),
        u'Bayern': (BAYRISCH, ),
        u'bayr,. österr.': (BAYRISCH, OESTERR, ),
        u'bayrisch, österr.': (BAYRISCH, OESTERR, ),
        u'bayr.': (BAYRISCH, ),
        u'bayr., österr., schweiz.': (BAYRISCH, OESTERR, SCHWEIZ, ),
        u'bayr., österr.': (BAYRISCH, OESTERR, ),
        u'bei kleinen Jungs, verniedlichend': (VERHUELL, ),
        u'beleidigend': (ABWERTEND, ),
        u'berl.': (BERLIN, ),
        u'berlin.': (BERLIN, ),
        u'berlinerisch': (BERLIN, ),
        u'Berlinerisch': (BERLIN, ),
        u'berl. scherzhaft': (BERLIN, SCHERZHAFT, ),
        u'berl. veraltend': (BERLIN, VERALTEND, ),
        u'Berl. Spruch': (BERLIN, ),
        u'besonders süddeutsch': (SUEDDT, ),
        u'Betonung auf 1. Silbe, norddt.': (NORDDT, ),
        u'bibl.': (BIBEL, ),
        u'bibl. Zitat': (BIBEL, ),
        u'biblisch': (BIBEL, ),
        u'biblisch, veraltet, auch ironisch': (BIBEL, VERALTET, IRONISCH, ),
        u'bildl.': (BILDLICH, ),
        u'bildlich': (BILDLICH, ),
        u'bildungsspr.': (GEHOBEN, ),
        u'bildungssprachlich': (GEHOBEN, ),
        u'bildungssprachlich, selten': (GEHOBEN, ),
        u'bildungssprachlich, veraltet': (GEHOBEN, VERALTET, ),
        u'biol.': (BIOLOGIE, ),
        u'bis 1916': (HIST, ),
        u'bis 1948': (HIST, ),
        u'bis 1990': (HIST, ),
        u'bis 1999': (HIST, ),
        u'Bodensee': (ALEMANN, ),
        u'bot.': (BIOLOGIE, ),
        u'bot. veraltet': (BIOLOGIE, VERALTET, ),
        u'bot., veraltet': (BIOLOGIE, VERALTET, ),
        u'Bundeswehr-Jargon': (),
        u'bürokrat./jurist.': (PAPIERDEUTSCH, ),
        u'chem.': (),
        u'christlich-relig.': (RELIGION, ),
        u'DDR': (DDR, ),
        u'derb': (DERB, ),
        u'deutschtümelnd': (),
        u'Drucktechnik': (DRUCKEREI, ),
        u'Druckwesen': (DRUCKEREI, ),
        u'dt. Plural Violen': (),
        u'ehemals DDR-Jargon, meist in der Mehrzahl': (DDR, ),
        u'Einfachschreibung': (),
        u'Eishockey': (),
        u'elsäss., sonst veraltet': (ALEMANN, ),
        u'elsässisch': (ALEMANN, ),
        u'elsässisch-pfälzisch': (ALEMANN, WESTMITTELDT, ),
        u'engl.': (ENGL, ),
        u'Engl.': (ENGL, ),
        u'engl. ausgesprochen': (),
        u'engl. Aussprache': (),
        u'engl. mil., veraltend': (ENGL, MILITAER, VERALTEND, ),
        u'euphemistisch': (VERHUELL, ),
        u'Ex-DDR-Jargon': (DDR, ),
        u'Fachjargon': (),
        u'fachspr.': (FACHSPRACHE, ),
        u'fachsprachlich': (FACHSPRACHE, ),
        u'fachsprachlich, speziell Bodenqualität': (FACHSPRACHE, ),
        u'fälschlich': (),
        u'fem., humor.': (SCHERZHAFT, ),
        u'fem., Jargon': (SALOPP, ),
        u'fig.': (BILDLICH, ),
        u'figurativ': (BILDLICH, ),
        u'auch fig.': (BILDLICH, ),
        u'formelhaft': (),
        u'frankfurterisch': (WESTMITTELDT, ),
        u'fr.': (FRZ, ),
        u'franz.': (FRZ, ),
        u'französisch': (FRZ, ),
        u'fränk.': (FRAENKISCH, ),
        u'fränk., bair.': (FRAENKISCH, BAYRISCH, ),
        u'fränkisch': (FRAENKISCH, ),
        u'frühes Mittelalter': (HIST, ),
        u'frz.': (FRZ, ),
        u'frz. Fremdwort': (FRZ, ),
        u'gängige Erweiterung': (),
        u'Gärtnersprache': (),
        u'Gastro.': (),
        u'geflügelter Ausspruch': (),
        u'geflügeltes Wort': (),
        u'geh.': (GEHOBEN, ),
        u'ggf. ironisch, veraltet': (IRONISCH, VERALTET, ),
        u'ggf. leicht iron.': (IRONISCH, ),
        u'gelockertes Schwäbisch': (SUEDDT, UGS, ),
        u'gilt als politisch inkorrekt': (ABWERTEND, ),
        u'Graubünden': (SCHWEIZ, ),
        u'griech.': (GRIECH, ),
        u'griechisch': (GRIECH ),
        u'halb-scherzhaft': (SCHERZHAFT, ),
        u'hamburgerisch': (NORDDT, ),
        u'häufige Erweiterung': (),
        u'häufige Erweiterung, Verlautbarungssprache': (PAPIERDEUTSCH, ),
        u'häufige Verstärkung': (),
        u'häufig als: das ist ja wohl ...': (),
        u'hess.': (WESTMITTELDT, ),
        u'hessich': (WESTMITTELDT, ),
        u'herablassend': (ABWERTEND, ),
        u'Heute ...': (),
        u'hist.': (HIST, ),
        u'histor.': (HIST, ),
        u'histor., ital. u. frz.': (HIST, ITAL, FRZ, ),
        u'histor., NS-Zeit': (NAZ, ),
        u'historisch': (HIST, ),
        u'hochgestochen': (GEHOBEN, ),
        u'humor.': (SCHERZHAFT, ),
        u'humoristisch zitierte Werbefloskel': (SCHERZHAFT, ),
        u'humoristisch': (SCHERZHAFT, ),
        u'im 17. Jhd.': (HIST, ),
        u'im Kontext Verhör': (),
        u'immer mit Possessivartikel: seine F. - ironisierend': (IRONISCH, ),
        u'iron.': (IRONISCH, ),
        u'ironisch': (IRONISCH, ),
        u'ironisch altertümelnd': (IRONISCH, ALTERTUEMLICH, ),
        u'ironisch, pseudo-altertümelnd': (IRONISCH, ALTERTUEMLICH, ),
        u'ironisch, salopp': (IRONISCH, SALOPP, ),
        u'ironisch, u.a. krim., nur Perfekt = ist ausgeflogen': (IRONISCH, ),
        u'ironisch, ursprünglich Filmtitel': (IRONISCH, ),
        u'ironisierend': (IRONISCH, ),
        u'leicht iron.': (IRONISCH, ),
        u'it., kors.': (ITAL, ),
        u'ital.': (ITAL, ),
        u'ital., Musik': (ITAL, MUSIK, ),
        u'italienisch': (ITAL, ),
        u'Jägerspr.': (JAEGER, ),
        u'Jägersprache': (JAEGER, ),
        u'Jargon einer Studentenverbindung': (),
        u'Jargon in u.a. bestimmten Sport- u. anderen Szenen': (),
        u'journal.': (),
        u'journalistisch, administrativ': (),
        u'Jugendsprache': (JUGEND, ),
        u'Jugendsprache, Substandard': (JUGEND, ),
        u'jugendsprachlich': (JUGEND, ),
        u'jugendsprachlich 2009': (JUGEND, ),
        u'jur.': (PAPIERDEUTSCH, ),
        u'jur., veraltet': (PAPIERDEUTSCH, VERALTET, ),
        u'Juristendeutsch': (PAPIERDEUTSCH, ),
        u'juristisch': (PAPIERDEUTSCH, ),
        u'kärntnerisch': (OESTERR, ),
        u'Kaufmannsspr.': (),
        u'kaufm.': (),
        u'kaufm., jur.': (PAPIERDEUTSCH, ),
        u'Kaufmannssprache': (),
        u'Kindersprache': (),
        u'kindersprachlich': (),
        u'Kochkunst': (),
        u'kölsch': (WESTMITTELDT, ),
        u'Kölsch': (WESTMITTELDT, ),
        u'kontextabhängig': (),
        u'krim.': (),
        u'landschaftlich': (LANDSCH, ),
        u'landschaftlich, selten': (LANDSCH, ),
        u'landschaftlich, selten in dieser Bedeutung': (LANDSCH, ),
        u'lat.': (LATEIN, ),
        u'Lat.': (LATEIN, ),
        u'lat. veraltet': (LATEIN, VERALTET, ),
        u'lateinisch': (LATEIN, ),
        u'lausitzisch': (OSTMITTELDT, ),
        u'leicht abwertend': (ABWERTEND, ),
        u'leicht ironisch': (IRONISCH, ),
        u'leicht resignierend': (),
        u'lettisch': (LETT, ),
        u'liechtenst.': (),
        u'linksrhein. bis z. Neckar': (ALEMANN, ),
        u'lit.': (LIT, ),
        u'lit.; journalistisch': (LIT, ),
        u'lit., abwertend': (LIT, ABWERTEND, ),
        u'lit., scherzhaft': (LIT, SCHERZHAFT, ),
        u'lit., veraltet': (LIT, VERALTET, ),
        u'literar.': (LIT, ),
        u'literarisch': (LIT, ),
        u'locker, leicht humorvoll': (UGS, SCHERZHAFT, ),
        u'lockeres Ruhrdeutsch': (UGS, WESTMITTELDT, ),
        u'luxemburgisch': (LUXEMB, ),
        u'med.': (MEDIZIN, ),
        u'mediensprachlich': (),
        u'meist iron.': (IRONISCH, ),
        u'meist ironisch': (IRONISCH, ),
        u'meist milit.': (MILITAER, ),
        u'meist Plur.: Ambitionen': (),
        u'meist Plural': (),
        u'meist Plural: Hallus': (),
        u'meist Plural: Niederschläge': (),
        u'meist Plural: Teds': (),
        u'meist Plural: in Schwulitäten': (),
        u'meist selbstironisch': (IRONISCH, ),
        u'mil. Kommando': (MILITAER, ),
        u'mil., meist fig.': (MILITAER, BILDLICH, ),
        u'mil., Spezialisierung': (MILITAER, ),
        u'mil., veraltet': (MILITAER, ),
        u'militärisch': (MILITAER, ),
        u'mil.': (MILITAER, ),
        u'Mil.': (MILITAER, ),
        u'mil., mit Nummer': (MILITAER, ),
        u'Milieu-Jargon': (SALOPP, ),
        u'Militär': (MILITAER, ),
        u'Militärjargon': (),
        u'mil., meist übertragen': (MILITAER, UEBERTRAGEN, ),
        u'militärisch, kommerziell': (MILITAER, ),
        u'mit Geste': (),
        u'mit ansatzweise resignativem Unterton': (),
        u'möglicherweise regional': (LANDSCH, ),
        u'möglicherweise veraltend': (VERALTEND, ),
        u'mt Geste': (),
        u'Mosel-Main-Region, schweiz.': (ALEMANN, SCHWEIZ, ),
        u'nachgestellt; veraltet': (VERALTET, ),
        u'Nachrichtensprache': (), 
        u'Nazi-Jargon': (NAZ, ),
        u'Nazi-Jargon, heute meist ironisch': (NAZ, IRONISCH, ),
        u'Neckarraum, selten': (LANDSCH, ),
        u'neol., ironisch': (IRONISCH, ),
        u'neu seit 2010': (),
        u'niederdt.': (NORDDT, ),
        u'niederdeutsch': (NORDDT, ),
        u'niederl.': (NIEDERL, ),
        u'niederländisch': (NIEDERL, ),
        u'niederrhein., veraltet': (NORDDT, VERALTET),
        u'Niederrhein, Westfalen': (NORDDT, WESTMITTELDT, ),
        u'niederrheinisch': (NORDDT, ),
        u'niedersächs.': (NORDDT, ),
        u'norddeutsch': (NORDDT, ),
        u'Norddeutsch': (NORDDT, ),
        u'norddt.': (NORDDT, ),
        u'norddt. gebietsweise, Berlin': (NORDDT, BERLIN, ),
        u'norddt., salopp': (NORDDT, SALOPP, ),
        u'norddt., süddt. verstreut': (NORDDT, ),
        u'nordniedersächsisch': (NORDDT, ),
        u'Norm-Sprache': (),
        u'NS-Jargon': (NAZ, ),
        u'nur Plur.': (),
        u'nur Plur., veraltet oder scherzhaft-ironisch': (VERALTET, SCHERZHAFT, IRONISCH, ),
        u'nur Plural': (),
        u'nur in speziellen Kontexten': (),
        u'nur in Verbindung mit lächeln': (),
        u'oberdt.': (SUEDDT, MITTELDT, ),
        u'Obersächsisch': (OSTMITTELDT, ),
        u'oft fig.': (BILDLICH, ),
        u'oft Plur.: Sachzwänge': (),
        u'oft Plural': (),
        u'oft Plural, fig.': (BILDLICH, ),
        u'oft iron.': (IRONISCH, ), 
        u'oft ironisch': (IRONISCH, ),
        u'ökon.': (),
        u'ostdeutsch-jugendsprachlich': (OSTDT, JUGEND, ),
        u'\'ost\'-deutsch scherzhaft': (OSTDT, SCHERZHAFT, ),
        u'ostdt.': (OSTDT, ),
        u'ostdt., norddt.': (OSTDT, NORDDT, ),
        u'österr.': (OESTERR, ),
        u'österreichisch': (OESTERR, ),
        u'österreichisch umgangssprachlich scherzhaft': (OESTERR, SCHERZHAFT, ),
        u'österr., schwäb., schweiz., tirol.': (OESTERR, ALEMANN, SCHWEIZ, ),
        u'österr., schweiz., bayr.': (OESTERR, SCHWEIZ, BAYRISCH, ),
        u'österr., schweiz.': (OESTERR, SCHWEIZ, ),
        u'österr., bay.': (OESTERR, BAYRISCH, ),
        u'österr. salopp': (OESTERR, SALOPP, ),
        u'österr., gebietsweise': (OESTERR, ),
        u'österr., regional': (OESTERR, ),
        u'österr., veraltend': (OESTERR, VERALTEND),
        u'Österreich': (OESTERR, ),
        u'ostfries.': (NORDDT, ),
        u'ostfränkisch': (FRAENKISCH, ),
        u'Ost-Sachsen': (OSTMITTELDT, ),
        u'Ost-Österreichisch': (OESTERR, ),
        u'ost-österr.': (OESTERR, ),
        u'Ostdeutschl.': (OSTDT, ),
        u'Ostpreußisch': (PREUSS, ),
        u'ost-, norddt., niederrhein.': (OSTDT, NORDDT, ),
        u'passiv': (),
        u'pathetisch': (),
        u'pej.': (ABWERTEND, ),
        u'persisch': (PERS, ),
        u'pfälzisch': (WESTMITTELDT, ),
        u'Pfälzisch': (WESTMITTELDT, ),
        u'plattdt.': (NORDDT, ),
        u'Plattdeutsch': (NORDDT, ),
        u'plural, lat.': (LATEIN, ),
        u'Plur. Smertnizy': (),
        u'poet.': (DICHTERISCH, ),
        u'poet., emphatisch': (DICHTERISCH, ),
        u'poetisch': (DICHTERISCH, ),
        u'polit.': (),
        u'Polizeijargon': (),
        u'Plur., bot.': (),
        u'Plur. Wasserreiser': (),
        u'plural': (),
        u'Plural': (),
        u'plural: Daten': (),
        u'meist plur.': (),
        u'pragmatisch': (),
        u'pragmatisch oder locker': (SALOPP, ),
        u'Pron.': (),
        u'psychol.': (),
        u'preußisch': (PREUSS, ),
        u'rätoromanisch': (SCHWEIZ, ),
        u'Raum Aachen': (WESTMITTELDT, ),
        u'Redewendungselement': (),
        u'regional': (LANDSCH, ),
        u'regional, abwertend': (LANDSCH, ABWERTEND, ),
        u'regional, alemannisch': (ALEMANN, ),
        u'relig.': (RELIGION, ),
        u'religiös': (RELIGION, ),
        u'regional: norddt.': (NORDDT, ),
        u'regional, österr.': (LANDSCH, OESTERR, ),
        u'regional, selten': (LANDSCH, ),
        u'regional, u.a. Ruhrdeutsch': (LANDSCH, ),
        u'regional, u.a. ruhrdt.': (LANDSCH, ),
        u'regional, veraltet': (LANDSCH, VERALTET, ),
        u'regional vereinzelt': (LANDSCH, ),
        u'relativ neu': (),
        u'respektvoll': (),
        u'Rhein., Plural Dönekes': (WESTMITTELDT, ),
        u'rheinisch': (WESTMITTELDT, ),
        u'Rheinisch': (WESTMITTELDT, ),
        u'Rheinland': (WESTMITTELDT, ),
        u'rhet., ling.': (),
        u'ruhrdt.': (WESTMITTELDT, ),
        u'ruhrdeutsch': (WESTMITTELDT, ),
        u'Ruhrdeutsch': (WESTMITTELDT, ),
        u'Ruhrdeutsch veraltend': (WESTMITTELDT, VERALTEND, ),
        u'Ruhrdeutsch, veraltend': (WESTMITTELDT, VERALTEND, ),
        u'Ruhrdeutsch, Rheinland': (WESTMITTELDT, ),
        u'Ruhrdeutsch, veraltet': (WESTMITTELDT, VERALTET, ),
        u'Ruhrdt.': (WESTMITTELDT, ),
        u'Ruhrdt., Westfälisch': (WESTMITTELDT, ),
        u'Ruhrdt., veraltet': (WESTMITTELDT, VERALTET, ),
        u'römisch': (LATEIN, ),
        u'rumänisch': (RUMAEN, ),
        u'russisch veraltet, 1944-92': (RUSS, VERALTET, ),
        u'russ.': (RUSS, ),
        u'sächs.': (OSTMITTELDT, ),
        u'salopp': (SALOPP, ),
        u'Sarkasmus': (IRONISCH, ),
        u'sarkastisch': (IRONISCH, ),
        u'sarkastischer DDR-Jargon': (DDR, IRONISCH, ),
        u'satirische Parodie auf den ehemals offiziellen DDR-Jargon': (DDR, IRONISCH, ),
        u'Sauerland, Bergisch': (WESTMITTELDT, ),
        u'scherzhaft': (SCHERZHAFT, ),
        u'scherzhaft, abwertend': (SCHERZHAFT, ABWERTEND, ),
        u'scherzhaft für nicht auffindbare Dateien': (SCHERZHAFT, ),
        u'scherzhaft gemeint': (SCHERZHAFT, ),
        u'scherzhaft, histor.': (SCHERZHAFT, HIST, ),
        u'scherzhaft-ironisch': (SCHERZHAFT, IRONISCH, ),
        u'scherzhaft oder abwertend': (SCHERZHAFT, ABWERTEND, ),
        u'scherzhaft, oft mit Orts-Attribut, z.B. Berliner Rohrperle': (SCHERZHAFT, ),
        u'scherzhaft, veraltend': (SCHERZHAFT, VERALTEND, ),
        u'scherzhaft, veraltet': (SCHERZHAFT, VERALTET, ),
        u'schwedisch historisch': (SCHWED, HIST, ),
        u'schweiz.': (SCHWEIZ, ),
        u'schweiz., Kanton Glarus': (SCHWEIZ ),
        u'schweiz., österr.': (SCHWEIZ, OESTERR, ),
        u'schweiz., regional': (SCHWEIZ, ),
        u'schweiz. Verwaltungsdeutsch': (SCHWEIZ, PAPIERDEUTSCH, ),
        u'schwäb.': (ALEMANN, ),
        u'schwäb., bad.': (ALEMANN, ),
        u'südtir., wallis.': (OESTERR, ),
        u'schwäb., bayr., österr.': (ALEMANN, BAYRISCH, OESTERR, ),
        u'schwäbisch': (ALEMANN, ),
        u'schwäbisch, abwertend': (ALEMANN, ABWERTEND, ),
        u'schwäbisch, stark abwertend': (ALEMANN, ABWERTEND, ),
        u'schwäbisch, veraltet': (ALEMANN, VERALTET, ),
        u'Schweiz': (SCHWEIZ, ),
        u'seemännisch': (SEEMANN, ),
        u'Seemannssprache': (SEEMANN, ),
        u'sehr veraltet': (VERALTET, ),
        u'selten': (),
        u'selten, abwertend': (ABWERTEND, ),
        u'siebenbürgisch-sächsisch': (OSTMITTELDT, ),
        u'simplifizierend': (),
        u'Slogan der SS': (NAZ, ),
        u'slow.': (),
        u'slowakisch': (SLOWAK, ),
        u'Sonderform': (),
        u'spa.': (SPAN, ),
        u'span.': (SPAN, ),
        u'Sport, Musik, Theat.': (MUSIK, ),
        u'Sportjournalismus': (),
        u'spöttelnd': (SPOETT, ),
        u'spöttisch': (SPOETT, ),
        u'stark abwertend': (ABWERTEND, ),
        u'südbadisch, allemannisch': (ALEMANN, ),
        u'südd.': (SUEDDT, ),
        u'süddeutsch': (SUEDDT, ),
        u'Süddeutsch': (SUEDDT, ),
        u'süddt.': (SUEDDT, ),
        u'süddt., aussterbend': (SUEDDT, VERALTEND, ),
        u'südd., österr.': (SUEDDT, OESTERR, ),
        u'süddt., z.T. mundartlich': (SUEDDT, LANDSCH, ),
        u'süddeutsch, österr.': (SUEDDT, OESTERR, ),
        u'südoberpfälzisch': (WESTMITTELDT, ),
        u'süd-österr.': (OESTERR, ),
        u'südtirol.': (LANDSCH, ),
        u'Szenejargon, Neol.': (),
        u'Szenesprache': (),
        u'technisch': (FACHSPRACHE, ),
        u'teil-werbesprachlich': (),
        u'teilweise rechtslastig': (),
        u'teilweise werbesprachlich': (),
        u'Theat.': (),
        u'thüringisch': (MITTELDT, ),
        u'Tierzucht': (),
        u'tirol.': (OESTERR, ),
        u'Tirol, vereinzelt': (OESTERR, ),
        u'tschechisch': (TSCHECH, ),
        u'u.a. ruhrdeutsch': (WESTDT, ),
        u'u.a. Ruhrdeutsch, veraltend': (LANDSCH, VERALTEND, ),
        u'u.a. Sport': (),
        u'übertr.': (UEBERTRAGEN, ),
        u'übertragen': (UEBERTRAGEN, ),
        u'Übertreibung': (),
        u'übertreibend': (),
        u'ugs.': (UGS, ),
        u'ungarisch': (UNGAR, ),
        u'Ungarn': (UNGAR, ),
        u'ungebräuchlich': (),
        u'unterfränkisch': (FRAENKISCH, ),
        u'Untertreibung': (),
        u'v.a. bei Tieren, griechisch': (GRIECH, ),
        u'veralt.': (VERALTET, ),
        u'varaltet': (VERALTET),
        u'veraltet, heute ironisierend': (VERALTET, IRONISCH, ),
        u'veraltet lit.': (VERALTET, DICHTERISCH, ),
        u'veraltend': (VERALTEND, ),
        u'veraltend, oft ironisch': (VERALTEND, IRONISCH, ),
        u'veraltet': (VERALTET, ),
        u'veraltet?': (VERALTET, ),
        u'veraltet, abwertend': (VERALTET, ABWERTEND, ),
        u'veraltet, Bayern': (VERALTET, BAYRISCH, ),
        u'veraltet, hochdt.': (VERALTET, ),
        u'veraltet, 1939-1945': (VERALTET, ),
        u'veraltet, 1904 bis 1920 und im 2. WK': (VERALTET, ),
        u'veraltet, 1918-1990': (VERALTET, ),
        u'veraltet, 1932 bis 1990': (VERALTET, ),
        u'veraltet, 1936-1945': (VERALTET, ),
        u'veraltet, 1937-1945': (VERALTET, ),
        u'veraltet, 1938-1942': (VERALTET, ),
        u'veraltet, 1938-1974': (VERALTET, ),
        u'veraltet, 1939-1940': (VERALTET, ),
        u'veraltet, bis 1980': (VERALTET, ),
        u'veraltet, bis 1973': (VERALTET, ),
        u'veraltet, bis 1964': (VERALTET, ),
        u'veraltet, bis 1961': (VERALTET, ),
        u'veraltet, bis 1948': (VERALTET, ),
        u'veraltet, bis 1945': (VERALTET, ),
        u'veraltet, bis 1935': (VERALTET, ),
        u'veraltet, bis 1930': (VERALTET, ),
        u'veraltet, bis 1927': (VERALTET, ),
        u'veraltet, bis 1926': (VERALTET, ),
        u'veraltet, bis 1924': (VERALTET, ),
        u'veraltet, bis 1918': (VERALTET, ),
        u'veraltet, bis 1900': (VERALTET, ),
        u'veraltet, bis 1890': (VERALTET, ),
        u'veraltet, gehoben': (VERALTET, GEHOBEN, ),
        u'veraltet, meist redensartlich': (VERALTET, ),
        u'veraltet od. regional': (VERALTET, LANDSCH, ),
        u'veraltet oder landschaftlich': (VERALTET, LANDSCH),
        u'veraltet, oft Plural: Gesichte': (VERALTET, ),
        u'veraltet, heute ironisch': (VERALTET, IRONISCH),
        u'veraltet / regional': (VERALTET, LANDSCH, ),
        u'veraltet, scherzhaft': (VERALTET, SCHERZHAFT, ),
        u'veraltet, süddt.': (VERALTET, SUEDDT),
        u'veraltet, Symbol': (VERALTET, ),
        u'Verballhornung': (),
        u'verlatend': (),
        u'Verstärkung': (),
        u'verniedlichend': (VERHUELL, ),
        u'verniedlichend, rheinisch': (VERHUELL, WESTMITTELDT, ),
        u'Verniedlichung; Filmfigur': (VERHUELL, ),
        u'Verstärkung, veraltend': (VERALTEND, ),
        u'Verwaltungsdeutsch': (PAPIERDEUTSCH, ),
        u'vornehmlich span.': (SPAN, ),
        u'vulg.': (VULGAER, ),
        u'Werbesprache': (),
        u'west- bis süddt. u. schweizerisch': (WESTDT, SUEDDT, SCHWEIZ, ),
        u'westdeutsch': (WESTDT, ),
        u'westf.': (WESTMITTELDT, ),
        u'westfälisch': (WESTMITTELDT, ),
        u'West-Sachsen': (OSTMITTELDT, ),
        u'westschweiz.': (SCHWEIZ, ),
        u'wienerisch': (OESTERR, ),
        u'Wortbildungselement': (),
        u'Wortbildungslement': (),
        u'Wortzusatz': (),
        u'zärtlich-ironisch': (IRONISCH, ),
        u'zeitgenössisch': (HIST, ),
        u'Zentral-Sachsen, vereinzelt': (OSTMITTELDT, ),
        u'zool.': (BIOLOGIE),
        u'zynisch': (IRONISCH, ABWERTEND),
}

OT_MARKERS_IGNORE = dict( [ (i, None) for i in
        (
            u'1,5%-1,8%',
            u'1 zu 1000',
            u'...',
            u'... doch noch',
            u'... scheinend',
            u'... sich herausstellen, dass o.ä.',
            u'"eins a"',
            u'= am nächsten, der kommt',
            u'+ Verb',
            u'ab 1365',
            u'ab 17. Jhd.',
            u'ab 1711',
            u'ab 1968',
            u'ab 1970',
            u'ab 1996',
            u'aber',
            u'abgekürzt',
            u'Abkürzung',
            u'Abstammung',
            u'Adresse',
            u'Aktien',
            u'AKW',
            u'Alias',
            u'althochdeutsch',
            u'als',
            u'als ob',
            u'am Computer',
            u'am Gewand',
            u'Amt',
            u'amtlich',
            u'an',
            u'an einem Datum',
            u'an einem Werk',
            u'an etwas',
            u'an jemandem',
            u'an jemandes Hals',
            u'angesichts',
            u'an, gegen',
            u'an/für',
            u'an/von',
            u'Anspruch',
            u'arbeitend/beschäftigt',
            u'Arbeitsplatz',
            u'Architektur',
            u'Arten von',
            u'Arzt',
            u'auch übertragen: Streit .. an',
            u'auf',
            u'auf jemanden',
            u'auf Kleidung',
            u'auf Yachten',
            u'auf frischer Tat',
            u'auf, nach',
            u'auf, über',
            u'auf der Welt',
            u'Aufstand',
            u'aus',
            u'aus der Blase',
            u'aus der Haft',
            u'aus, von',
            u'aus / durch',
            u'aus dem Bestand',
            u'Ausbildungsberuf',
            u'ausgestattet',
            u'Aussage',
            u'aussehen/herumlaufen',
            u'Ausruf',
            u'Bankett',
            u'Banknoten',
            u'Bann',
            u'Bauland, Gebiet',
            u'Baumwolle',
            u'befindlich / angesiedelt',
            u'bei',
            u'bei Archiven',
            u'bei etwas',
            u'bei jemandem',
            u'bei Körnern',
            u'bei Lebensversicherungen',
            u'bei Menschen',
            u'bei mir / uns',
            u'bei Suppen/Soßen, etc.',
            u'bei Säugetieren',
            u'bei Wolken',
            u'bei einer Krankheit',
            u'beim Arzt',
            u'beim Gedanken an',
            u'beim Menschen',
            u'beim Publikum',
            u'beleuchtet',
            u'Bergbau',
            u'beschreibt die Form',
            u'Besuch',
            u'betont, Emphase',
            u'Betonung auf e',
            u'Betonung auf \'eine\'',
            u'Betriebsjargon',
            u'bewegen',
            u'Bildbearbeitung',
            u'bilden', 
            u'Billard',
            u'bis',
            u'bis Version 6',
            u'Boden',
            u'Brief',
            u'Brot',
            u'Brummen',
            u'Buch',
            u'Buchbinden',
            u'Bucheinband',
            u'Buchhandel',
            u'Buchstaben einzeln ausgesprochen',
            u'bürgerlich',
            u'Büro',
            u'Burschenschaften',
            u'Cembalo,Orgel',
            u'chemisch falsch',
            u'Chinesisches Taipei',
            u'Codename',
            u'da',
            u'dahin gesagt',
            u'"das ist hier jetzt nicht die Frage"',
            u'dass',
            u'DDR-Währung',
            u'der Aufmerksamkeit',
            u'der Bonität',
            u'der Bundeswehr',
            u'der katholischen Kirche',
            u'der Kosten',
            u'der Macht',
            u'dem Namen / Begriff',
            u'der Physik',
            u'der Stasi',
            u'der Stimme',
            u'der Welt',
            u'der/dem - z.B. Druckerei',
            u'des Körpers',
            u'die Gelben',
            u'Diskussion',
            u'Dividende, Erbschaft',
            u'dran',
            u'dreschen',
            u'Druckersprache',
            u'dt. meist Plural: Antipasti',
            u'durch',
            u'durch ein Sieb',
            u'durcheinander',
            u'eben',
            u'Eimer',
            u'eine Information',
            u'einem bestimmten Zeitpunkt',
            u'einer Anleihe',
            u'einer Firma',
            u'einer Frau / einem Mann',
            u'einer Geldschuld',
            u'einer Gesellschaft',
            u'einer Meinung',
            u'einer Oberfläche',
            u'einer oder mehrer Personen',
            u'einer Optik',
            u'einer Sache',
            u'einer Seite',
            u'einer Skala',
            u'einer Software',
            u'einer Stadt',
            u'einer Stelle',
            u'einer Substanz',
            u'einer Wand',
            u'einer Zeitung',
            u'eines Amtes',
            u'eines Buches',
            u'eines Erregers',
            u'eines Flusses',
            u'eines Gedichts',
            u'eines Geschehens',
            u'eines Konfliktes',
            u'eines Kredits',
            u'eines Kunden an mich',
            u'eines Kunden mit einer Zahlung',
            u'eines Künstlers',
            u'eines Pferdes',
            u'eines Prominenten',
            u'eines Schiffes',
            u'eines Schriftstückes',
            u'Einfluss',
            u'Einheitenzeichen',
            u'Eiskunstlauf',
            u'einmal',
            u'Einschub',
            u'elektr.',
            u'erlangen',
            u'es',
            u'es geht ...',
            u'es gibt ...',
            u'es gibt da ...',
            u'es; mit einer Sache',
            u'etwas',
            u'etwas zu sein',
            u'etwas zu tun',
            u'etwas/mit etwas',
            u'fahren',
            u'Fahrrad',
            u'Farbe',
            u'Farbe, Metall',
            u'Fass',
            u'Fehler o.ä.',
            u'Femininum',
            u'festgeschrieben, bestimmt, gemacht o.ä.',
            u'Festigkeitsprüfung',
            u'Feuer',
            u'Film',
            u'Flammen',
            u'Flasche',
            u'Fleisch',
            u'Floskel',
            u'Formelzeichen',
            u'Frage',
            u'fühlen',
            u'für',
            u'für Kontakte',
            u'für Pferde, Ochsen',
            u'für Wein',
            u'für etwas',
            u'für jemanden',
            u'für jemanden, es',
            u'für, gegen',
            u'für, zu',
            u'für, um',
            u'für/um zu',
            u'für / um zu ...',
            u'Fußball',
            u'Gebäude',
            u'gefertigt',
            u'Gefühle',
            u'gegen',
            u'gegen, mit', 
            u'gegen/bei',
            u'gegen jemanden / etwas',
            u'gegenüber',
            u'gegenüber e. Gläubiger',
            u'gegenüber einem Gläubiger',
            u'gegenüber einem Kreditor',
            u'gehen / müssen / gehen müssen',
            u'ggü. Gläubigern',
            u'ggü. einem Gläubiger',
            u'ggüb. Gläubiger',
            u'ggüb. Gläubigern',
            u'gekommen',
            u'Geld',
            u'Geldbetrag',
            u'Gelände',
            u'gepeilt',
            u'Gesang',
            u'Geschichte',
            u'Geschäft',
            u'Gesicht',
            u'gesprochene Form',
            u'Getreide',
            u'getrieben o.ä.',
            u'Gewerbe',
            u'Gewicht',
            u'Grammatik',
            u'Haar',
            u'haben',
            u'haben / tragen',
            u'Halbleiter',
            u'Handarbeit',
            u'herumtreiben',
            u'haftungsbeschränkt',
            u'hätte',
            u'hell',
            u'heraus',
            u'herauspicken',
            u'hergestellt',
            u'hinter Flugzeugen',
            u'HNO',
            u'Holz',
            u'Holz, Erbsen',
            u'Hörer des Telefons',
            u'Hunde',
            u'jemanden',
            u'i.e.S. Zellteilung',
            u'IHK-Zertifikat, i.d. Schweiz Lehrausbildung mit EFZ',
            u'im philippinischen Raum',
            u'im weiteren Sinne',
            u'im Ausland',
            u'im Brief',
            u'im Frühjahr',
            u'im Haushalt',
            u'im Internet',
            u'im Konjunktiv: das wäre...',
            u'im Kopf',
            u'im Krankenhaus',
            u'im Leibe',
            u'im Marketing-Mix',
            u'im Mauerwerk',
            u'im Meer',
            u'im Mini-Apartment',
            u'im Norden',
            u'im Rennruderboot',
            u'im Süden',
            u'im Tonfall der \'neuen Empfindsamkeit\'',
            u'im Verdauungstrakt',
            u'imo',
            u'in',
            u'in Anzeigen',
            u'in Aufforderungen',
            u'in Deutschland',
            u'in Dosen',
            u'in Ecuador',
            u'in Formularen',
            u'in Fragen',
            u'in landwirtschaftlich genutztem Gebiet',
            u'in Moldawien',
            u'in Peru',
            u'in vielen Abwandlungen, Nachrichtensprache',
            u'in Wasser',
            u'in, zu',
            u'in \'Hintertreppenpsychologie\' u.ä.',
            u'in \'Küchenpsychologie\' u.ä.',
            u'in/bei',
            u'in: Wasser lassen',
            u'Industrie',
            u'Informatik',
            u'inoffiziell',
            u'Intensität o.ä.',
            u'irrtümlich',
            u'IT-Jargon',
            u'Jagd, Forst',
            u'Jahre, Tage',
            u'jemanden / etwas',
            u'Journalistensprache',
            u'Kalauer',
            u'Kanada, bis 1916',
            u'Kandidaten, Spieler',
            u'Karte',
            u'Kartenspiel',
            u'Katzen',
            u'keltisch',
            u'Keramik',
            u'Kleidung',
            u'Kloster',
            u'Kohlebergwerk',
            u'können',
            u'kroatisch',
            u'Kühe',
            u'kundenspezifisch',
            u'Küstenbewohner',
            u'Lächeln',
            u'Lager',
            u'Landwirtschaft',
            u'lassen',
            u'lebend',
            u'Lebensmittel',
            u'Lese-/Schreibop.',
            u'Level \'neue Empfindsamkeit\'',
            u'liefern',
            u'liegen',
            u'Löten',
            u'machen',
            u'Macht, Amt',
            u'Männchen',
            u'männlich',
            u'Markenbegriff',
            u'Markenname',
            u'Maschine',
            u'Maskulinum',
            u'max. 0,3%',
            u'medizinisch',
            u'mehr',
            u'meist Vergangenheits-Tempora: hat sich erledigt ...',
            u'mhdt.',
            u'Messer',
            u'Metall',
            u'Milch',
            u'min. 3,5%',
            u'mit',
            u'mit/bei',
            u'mit/bei etwas',
            u'mit Dativ',
            u'mit einem Stethoskop',
            u'mit etwas',
            u'mit Fett, im Backofen',
            u'mit jemandem', 
            u'mit Geschenken, Fragen',
            u'mit Posten',
            u'mit Verb + Subj. davor; literarisch',
            u'mit, für',
            u'mit, über',
            u'mit, zu',
            u'mittelhochdeutsch',
            u'mittelniederdt.',
            u'MLM',
            u'Mode',
            u'Motor',
            u'Motor o.ä.',
            u'Motorrad',
            u'Münzwesen',
            u'Musik',
            u'müssen',
            u'Mystik',
            u'nach',
            u'nach Alkoholkonsum',
            u'nach Alkoholtrunk',
            u'nach dem Julfest',
            u'nach / zu / in ...',
            u'Nase',
            u'Nassau',
            u'negativ',
            u'Negativ',
            u'neologistisch',
            u'neuer Systeme',
            u'Netzwerk',
            u'Netzwerktechnologie',
            u'neudeutsch',
            u'Neutrum',
            u'NF',
            u'noch',
            u'Nordsee',
            u'nur Festland',
            u'o.ä.',
            u'ob',
            u'obendrauf',
            u'objektorientiert',
            u'Oder',
            u'oder: halten',
            u'oder: sein',
            u'oder: unterworfen haben',
            u'ohne inneres Gerüst',
            u'offiziell',
            u'ohne Peripherie',
            u'oris',
            u'Parlament',
            u'Partizip 2 = erkoren; veraltet',
            u'Person',
            u'Pferd',
            u'Pferdefarbe',
            u'Platte, Fliese',
            u'Plur.: Schauerleute',
            u'Polen',
            u'politischer Euphemismus 2009',
            u'Populärversion eines Zitats von von Clausewitz',
            u'positiv',
            u'Positiv',
            u'Preis',
            u'Preise, Löhne',
            u'Problem',
            u'Prozessbezeichnung',
            u'Prüfungsanwärter',
            u'Psycho-Jargon',
            u'Qualifikationslevel',
            u'Publikum/Leser',
            u'Raufhändel',
            u'reagieren',
            u'Rechnung',
            u'reden',
            u'Redensart',
            u'reduziert, zurückgenommen o.ä.',
            u'Reitsport',
            u'Rind',
            u'Rollenfach bei Theater und Operette',
            u'rum',
            u'Rundfunk-/Fernsehranstalt',
            u'sagen',
            u'sagen o.ä.', 
            u'Schach',
            u'Scheck',
            u'Schiff',
            u'Schiff oder Flugzeug',
            u'schließen',
            u'schon',
            u'Schuss',
            u'schwanger werden',
            u'schweiz. Schreibung',
            u'See und Luft',
            u'sehr',
            u'sein',
            u'sein Geld',
            u'sein an etwas',
            u'sein in etwas',
            u'seine Jugend',
            u'selbst',
            u'Selbstvermarktungsbegriff',
            u'sich',
            u'siehe dort',
            u'sitzen',
            u'so',
            u'Speisen',
            u'Spessart',
            u'Spezialisierung',
            u'speziell: Hunde',
            u'speziell: große Säugetiere',
            u'Spielfigur',
            u'Sport',
            u'Spottbezeichnung',
            u'Spottname',
            u'sprechen o.ä.',
            u"sprich 'gerne haben', oder Deftigeres",
            u'Sprichwort',
            u'Spruch',
            u'Steak',
            u'stehen',
            u'stehend',
            u'Steuern',
            u'Stimme',
            u'Stirn, Augenbrauen',
            u'Straßburg',
            u'Streit',
            u'streng bis ärgerlich im Ton',
            u'Sturm, Erregung',
            u'Stuten',
            u'suchen',
            u'Südtirol',
            u'Symbol',
            u'Szenejargon',
            u'Tatsache',
            u'Taxi',
            u'temporäre Selbstbezeichnung',
            u'Telefon',
            u'Text',
            u'Textilien',
            u'Theater',
            u'Theaterstück',
            u'Thema',
            u'Tier',
            u'Tonband',
            u'trächtig werden',
            u'Treffen, Versammlung',
            u'Turnen',
            u'u.a. Arbeitswelt',
            u'über',
            u'über Vokal',
            u'über, um',
            u'über, um, wegen',
            u'über, wegen',
            u'überdacht',
            u'über jemanden',
            u'um',
            u'um nichts',
            u'um etwas',
            u'um, wegen',
            u'unabsichtlich',
            u'unfachmännisch',
            u'Universität',
            u'Unkraut',
            u'unter',
            u'unter Wasser',
            u'urheberrechtlich',
            u'USA',
            u'u.a. Jägersprache für Wildschweine',
            u'verbrieften) Forderungen',
            u'vergoren',
            u'Vermögen',
            u'verstreut',
            u'vielleicht',
            u'Vogel',
            u'vom Schlachttier',
            u'von',
            u'von Boden',
            u'von Daten',
            u'von Deutschland',
            u'von Dokumenten',
            u'von Ehepartnern',
            u'von etwas',
            u'von Geschäften',
            u'von Gleichaltrigen',
            u'von hier',
            u'von Holz',
            u'von Kunden an mich',
            u'von Maßnahmen',
            u'von Metallen',
            u'von Tieren',
            u'von Wein',
            u'von Wein, Wasser',
            u'von Zahnrädern',
            u'von einem Staat',
            u'von jemandem',
            u'von jemanden',
            u'vor',
            u'vor Lachen',
            u'vor Wut',
            u'vor Zahlwörtern',
            u'Vormittag',
            u'vorkommend',
            u'Warenversand',
            u'Wasser',
            u'Weberei',
            u'wegen',
            u"wegen ..., für ..., oder mit Kontextangabe, z.B. 'dem Gericht'",
            u'wegen, für',
            u'wegen, um',
            u'weinen können',
            u'Wellen',
            u'werden',
            u'Werkstück',
            u'Werkzeug',
            u'Wetter',
            u'Wettkampf',
            u'Wildtiere',
            u'Wohnung',
            u'wollen',
            u'wonach...',
            u'wörtlich',
            u'Wünsche',
            u'Wurst',
            u'Zahl',
            u'Zeit',
            u'zu',
            u'zu beobachten',
            u'zu einem Testament',
            u'zu etwas',
            u'zu jemandem',
            u'zu jm.',
            u'zuflüstern o.ä.',
            u'zum Befestigen',
            u'z. B. bei einer Matrix',
            u'z. B. des Blutes',
            u'z. B. für Farbe',
            u'z.B. am Bahnhof',
            u'z.B. Druckerei',
            u'z.B. Grundkenntnisse',
            u"z.B. 'sich dies als notwendig erweisen'",
            u'z.B. Einzelstück, Einzelmeinung',
            u'z.B. sich ... helfen',
            u'z.B. sich ... versöhnen',
            u'z.B. spannend',
            u'z.B. von Wellen',
            u'z.B. Wald- und Wiesen-Pädagogik',
            u'zu verstehen als: den genau bzw. wörtlich genommen übernächsten Freitag',
            u'zu verstehen als: nächste Woche Freitag',
            u'zwischen',
        )
] )
