name: test
on:
  push:
      branches:
      - 'main'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.2

      - name: Prepare java
        uses: actions/setup-java@v4.1.0
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install clojure tools-deps
        uses: DeLaGuardo/setup-clojure@13.4
        with:
          cli: 1.12.1.1550

      - name: Execute tests
        run: |
          export GIT_AUTHOR_NAME="ZDL-Lex"
          export GIT_AUTHOR_EMAIL="noreply@dwds.de"
          export GIT_COMMITTER_NAME="ZDL-Lex"
          export GIT_COMMITTER_EMAIL="noreply@dwds.de"
          clojure -T:build server && clojure -X:oxygen:client:server:test
        shell: bash
